---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadctl-sa
  namespace: eth-devnet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loadctl-role
  namespace: eth-devnet
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadctl-rb
  namespace: eth-devnet
subjects:
  - kind: ServiceAccount
    name: loadctl-sa
    namespace: eth-devnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loadctl-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadctl
  namespace: eth-devnet
spec:
  replicas: 1
  selector:
    matchLabels: {app: loadctl}
  template:
    metadata:
      labels: {app: loadctl}
    spec:
      serviceAccountName: loadctl-sa
      containers:
        - name: loadctl
          image: loadctl:dev
          imagePullPolicy: IfNotPresent
          env:
            - {name: NAMESPACE, value: "eth-devnet"}
            - {name: DEPLOYMENT, value: "loadgen"}
            - {name: CONTAINER, value: "loadgen"}
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: loadctl
  namespace: eth-devnet
spec:
  selector: {app: loadctl}
  type: NodePort        # 👈 this makes it accessible from your host
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 32080   # 👈 port you’ll use in browser (http://localhost:32080)
